import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarApp from "./components/NavBarApp";
import { ClientProvider } from "../context/ClientContext";
import { ProjectProvider } from '../context/ProjectContext';
import { TaskEntryProvider } from '../context/TaskEntryContext';
import { ContractorProvider } from "../context/ContractorContext";
import { CategoryProvider } from "../context/CategoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

    <TaskEntryProvider>
        <ProjectProvider>
          <ClientProvider>
            <ContractorProvider>
              <CategoryProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                  <NavBarApp/>
                    <main className="pt-[13vh] sm:pt-[11vh]">
                      {children}
                      </main>
                </body> 
              </CategoryProvider>
            </ContractorProvider>
          </ClientProvider>
        </ProjectProvider>
      </TaskEntryProvider>
    </html>
  );
}
